### ISSUE TITLE
Add N-Dimensional Raster

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/Intro-to-Desktop-GIS-with-QGIS#2]
Not beginner topic but critical for users of gridded Climate Models and Satellite data that often come in HDF5 format.

## TODO: New intermediate page on Rasters
- [x] "Bands" - what is a Band
- [x] N-Dim raster (get material from Xarray docs), e.g. Bands over Time
- [x] Common formats - HDF5/netcdf, Zarr/Kerchunk
