### ISSUE TITLE
Add Cloud Optimized Formats

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/Intro-to-Desktop-GIS-with-QGIS#3]
Not a beginner topic but these format are encountered more often now, and people might need to know what they are.

## TODO: Sub page on Formats
Should this be split across Vector and Raster or be a Cloud Optimized page?

- [x] Basic of all cloud optimized - read an index, only return the part you need (save $ and time)
- [x] File Based
    - [x] Vector
        - [x] Flatgeobuf
        - [x] GeoParquet
        - [x] Cloud Optimized Point Cloud (COPC)
     - [x] Raster
         - [x] Cloud Optimized Geotiff
         - [x] Zarr (or Zarr like Kerchunk)  

Not quite optimized:
- [ ] Tiling
    - [ ] XYZ tiling, WMTS
    - [ ] Mapbox Vector Tiles - in [QGIS](https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector_tiles/vector_tiles_properties.html)
- [ ] geojson

**Comment by wildintellect** [comment]
new branch https://github.com/developmentseed/Intro-to-Desktop-GIS-with-QGIS/tree/cloud-formats

**Comment by wildintellect** [comment]
Need another section on cloud native formats (optimized often is for analysis)


- MVT
- Protobuf
- geojson
- mbtiles/pmtiles
- ?

@geohacker any other key formats people need to know about?

**Comment by geohacker** [comment]
I see you have already included faltgeobuff and geoparquet. This looks great!
